### ISSUE TITLE
How does this work with large bitmaps? 

### ISSUE THREAD

**Issue by Bajix** [SalvatorePreviti/roaring-node#24]
I thought that roaring bitmaps were supposed to support arbitrary size bitmaps but I fail to see how that's possible with this as written. Does this only support 32 bits? I need at least 42 bits for my use case.

**Comment by lemire** [comment]
The standard is 32-bit but there are 64-bit extensions.

**Comment by Bajix** [comment]
Can you provide an example of 64 bit use? This works with BigInt?

**Comment by lemire** [comment]
Pilosa has a 64-bit Roaring index.

**Comment by Bajix** [comment]
Pilosa's only available on Go, Java and Python though? It looks like I can just use node-bigint for my use-case, so conceivably I could just use that instead and serialize to/from base 64, but ideally I would use roaring-node. If you could provide an example of using the roaring-node 64-bit extension then I'll go that direction, otherwise I might just take the easy route here and use BigInt.

**Comment by lemire** [comment]
There are various 64-bit extensions in Java, Go, C++. The standard, cross-platform format, is deliberately 32-bit.

**Comment by SalvatorePreviti** [comment]
Since JS does not support properly 64 bits, and numbers can store only up to 53 bits of integer without error, and because an implementation using BigInt will be slow, complicated to use and to implement, I don't think extending this library to support 64 bit would add any benefit. Is possible to define a Map<number, RoaringBitmap32> and write a wrapper around it to support number larger than 32 bits, however this has limitations and issues in terms of memory consumption and usability.

**Comment by Bajix** [comment]
Have you considered doing this by way of Rust FFI?
